### ISSUE TITLE
Failed to activate the japanese-wrap package

### ISSUE THREAD

**Issue by nutcase** [raccy/japanese-wrap#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [japanese-wrap](https://github.com/raccy/japanese-wrap) package, v0.2.4

### Stack Trace

Failed to activate the japanese-wrap package

```
At undefined is not a function

TypeError: undefined is not a function
  at Function.module.exports.UnicodeUtil.getRangeListByName (/Users/takamatsu/.atom/packages/japanese-wrap/lib/unicode-util.coffee:19:19)
  at JapaneseWrapManager.module.exports.JapaneseWrapManager.setupCharRegexp (/Users/takamatsu/.atom/packages/japanese-wrap/lib/japanese-wrap-manager.coffee:113:25)
  at new JapaneseWrapManager (/Users/takamatsu/.atom/packages/japanese-wrap/lib/japanese-wrap-manager.coffee:9:6)
  at Object.module.exports.activate (/Users/takamatsu/.atom/packages/japanese-wrap/lib/japanese-wrap.coffee:54:28)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:445:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:343:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:52:25)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
atom-runner, v2.3.0
autocomplete-plus, v2.7.1
autocomplete-ruby, v0.0.1
file-icons, v1.5.2
highlight-line, v0.10.1
japanese-wrap, v0.2.4
jsformat, v0.7.18
language-nginx, v0.4.0
language-unity-shaderlab, v1.0.1
linter, v0.12.0
linter-ruby, v0.1.4
minimap, v4.7.2
minimap-git-diff, v4.1.2
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
same issue here.

**Comment by zyobuden** [comment]
I have a same problem.

**Comment by jsakamoto** [comment]
me too.

**Comment by tomoya** [comment]
:tada:

**Comment by uchikoshi22** [comment]
working after updating from 0.2.4 to 0.2.7 on windows
